{/* <script id="tailwind-config"> */ }
tailwind.config = {
    darkMode: "class",
    theme: {
        extend: {
            colors: {
                "on-secondary-container": "#005a3c",
                "surface-variant": "#e2d7ff",
                "error": "#b41340",
                "surface-container": "#ede4ff",
                "error-container": "#f74b6d",
                "inverse-primary": "#8582ff",
                "secondary": "#006947",
                "surface-tint": "#4a40e0",
                "surface-container-highest": "#e2d7ff",
                "on-secondary": "#c8ffe0",
                "primary-fixed": "#9795ff",
                "surface-container-lowest": "#ffffff",
                "on-primary-fixed": "#000000",
                "on-tertiary-fixed-variant": "#645000",
                "on-tertiary-fixed": "#433500",
                "tertiary-fixed-dim": "#eec200",
                "on-primary-container": "#14007e",
                "inverse-surface": "#10062d",
                "inverse-on-surface": "#a296c4",
                "outline": "#7b719c",
                "on-error": "#ffefef",
                "tertiary-dim": "#614d00",
                "surface-container-low": "#f5eeff",
                "secondary-container": "#69f6b8",
                "on-secondary-fixed": "#00452d",
                "on-primary": "#f4f1ff",
                "background": "#faf4ff",
                "primary-container": "#9795ff",
                "outline-variant": "#b2a6d5",
                "surface-container-high": "#e8deff",
                "surface-bright": "#faf4ff",
                "secondary-dim": "#005c3d",
                "on-error-container": "#510017",
                "surface-dim": "#dacdff",
                "surface": "#faf4ff",
                "error-dim": "#a70138",
                "primary-dim": "#3d30d4",
                "on-surface-variant": "#5f557f",
                "tertiary": "#6f5900",
                "secondary-fixed": "#69f6b8",
                "secondary-fixed-dim": "#58e7ab",
                "tertiary-container": "#fed01b",
                "on-background": "#32294f",
                "primary-fixed-dim": "#8885ff",
                "tertiary-fixed": "#fed01b",
                "on-tertiary-container": "#594700",
                "primary": "#4a40e0",
                "on-primary-fixed-variant": "#1a0099",
                "on-secondary-fixed-variant": "#006544",
                "on-tertiary": "#fff2d3",
                "on-surface": "#32294f"
            },
            fontFamily: {
                "headline": ["Plus Jakarta Sans"],
                "body": ["Manrope"],
                "label": ["Plus Jakarta Sans"]
            },
            borderRadius: { "DEFAULT": "1rem", "lg": "2rem", "xl": "3rem", "full": "9999px" },
        },
    },
}